/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChangeLang: typeof import('./src/components/changeLang.vue')['default']
    MainLayout: typeof import('./src/components/mainLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanCode: typeof import('./src/components/scanCode.vue')['default']
  }
}
